### ISSUE TITLE
Remove Build folder error

### ISSUE THREAD

**Issue by purushottam-io** [fransyozef/generate-nft-metadata#1]
PS C:\Users\User\Desktop\Oiyer\generate-nft-metadata> npm run generate:fromMetadataJsonAndLayers

> generate-nft-metadata@1.1.4 generate:fromMetadataJsonAndLayers
> npm run clean:build && node utils/generateFromMetadataJsonAndLayers.js

> generate-nft-metadata@1.1.4 clean:build
> rm -Rf build

'rm' is not recognized as an internal or external command,
operable program or batch file.

error in window 10

**Comment by purushottam-io** [comment]
error in package script for window 10

**Comment by purushottam-io** [comment]
you can put rmdir instead of rm -Rf
like it 
"clean:build": "rmdir  build"

**Comment by fransyozef** [comment]
nah .. 

`rmdir build` won't work on mac when the build folder is not empty. I use mac for development, so I need this.

You could use Git Bash as your terminal (rm is supported there). It's documented in the README :)
